apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanlife-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanlife-frontend
  template:
    metadata:
      labels:
        app: vanlife-frontend
    spec:
      containers:
        - name: vanlife-frontend
          image: koceilabeast/vanlife-frontend:v2
          ports:
            - containerPort: 80
